pool:
  name: Default
  demands: npm

trigger:
 branches:
   include:
     - main
steps:

- task: TfxInstaller@3
  inputs:
    checkLatest: true

- task: QueryAzureDevOpsExtensionVersion@3
  inputs:
    connectTo: VsTeam
    connectedServiceName: 'VS marketplace'
    publisherId: 'VahidFarahmandian'
    extensionId: 'JingetQueryExecutor'
    versionAction: 'Patch'
    outputVariable: 'Task.Extension.Version'
- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: '$(System.DefaultWorkingDirectory)'
    publisherId: 'VahidFarahmandian'
    extensionId: 'JingetQueryExecutor'
    extensionName: 'Jinget Query Executor'
    extensionVersion: '$(Task.Extension.Version)'
    updateTasksVersion: true
    updateTasksVersionType: 'patch'
    extensionVisibility: 'private'
    extensionPricing: 'free'

- task: CopyFiles@2
  inputs:
    Contents: "**/*.vsix"
    TargetFolder: "$(Build.ArtifactStagingDirectory)"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(ArtifactName)'